src/bean/BillingAddress.java
package bean;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.hibernate.validator.constraints.NotBlank;

@ManagedBean
@ViewScoped
public class BillingAddress {
	
	@NotBlank(message="Address Required")
	private String address1;
	
	private String address2;
	
	private String address3;
	
	@NotBlank(message="Country required")
	private String country;
	
	@NotBlank(message="City required")
	private String city;
	
	@NotBlank(message="State required")
	private String state;
	
	@NotBlank(message="Zip required")
	private String zip;
	
	private int BillingId;
	
	public BillingAddress() {
		super();
		this.address1 = "";
		this.address2 = "";
		this.address3 = "";
		this.country = "";
		this.city = "";
		this.state = "";
		this.zip = "";
		this.BillingId = 0;
	}

	public String getAddress1() {
		return address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getAddress3() {
		return address3;
	}

	public void setAddress3(String address3) {
		this.address3 = address3;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZip() {
		return zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public Object getBillingId() {
		return BillingId;
	}
	
	public void setBillingId(int BillingId) {
		this.BillingId = BillingId;
	}
}

src/bean/CreditCard.java
package bean;

import java.util.Date;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotBlank;

@ManagedBean
@ViewScoped
public class CreditCard {

	@NotBlank(message="Card Number Required")
	@Size(min=16, max=16)
	private String number;
	
	@NotNull(message="Date Required")
	@NotBlank(message="Date Required")
	private Date exDate;
	
	@NotBlank(message="CCV Required")
	@NotNull(message="CCV Required")
	private String ccv;
	
	@NotBlank(message="Name Required")
	private String nameOnCard;
	
	private int billingAddressID;
	
	private int CardId;
	
	public CreditCard() {
		super();
		this.number = "";
		this.exDate = new Date();
		this.ccv = "";
		this.nameOnCard = "";
		this.billingAddressID = -1;
		this.CardId = 0;
		
	}

	public String getNumber() {
		return number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public Date getExDate() {
		return exDate;
	}

	public void setExDate(Date exDate) {
		this.exDate = exDate;
	}

	public String getCcv() {
		return ccv;
	}

	public void setCcv(String ccv) {
		this.ccv = ccv;
	}

	public String getNameOnCard() {
		return nameOnCard;
	}

	public void setNameOnCard(String nameOnCard) {
		this.nameOnCard = nameOnCard;
	}

	public int getBillingAddressID() {
		return billingAddressID;
	}

	public void setBillingAddressID(int billingAddressID) {
		this.billingAddressID = billingAddressID;
	}

	public Object getCardId() {
		return CardId;
	}
	
	public void setCardId(int CardId) {
		this.CardId = CardId;
	}
}

WebContent/AddressInfo.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:fs="http://xmlns.jcp.org/jsf/passthrough">

	<ui:composition template="/layouts/CommonLayout.xhtml">
		<ui:define name="title">Address Information</ui:define>
		<ui:define name="common-content">
			<div align="center">
			<h:form>
				<!-- Get the address 1 field -->
				<h:inputText value="#{mailAddress.address1}" id="address1" fs:placeholder="Address 1"/>
				<div class="error-message"><h:message for="address1"/></div><br/>
				<!-- Get the address 2 field -->
				<h:inputText value="#{mailAddress.address2}" id="address2" fs:placeholder="Address 2"/>
				<div class="error-message"><h:message for="lastName"/></div><br/>
				<!-- Get the address 3 field -->
				<h:inputText value="#{mailAddress.address3}" id="address3" fs:placeholder="Address 3"/>
				<div class="error-message"><h:message for="address3"/></div><br/>
				<!-- Get the Country field -->
				<h:inputText value="#{mailAddress.country}" id="country" fs:placeholder="Country"/>
				<div class="error-message"><h:message for="country"/></div><br/>
				<!-- Get the city field -->
				<h:inputText value="#{mailAddress.city}" id="city" fs:placeholder="City"/>
				<div class="error-message"><h:message for="city"/></div><br/>
				<!-- Get the state -->
				<h:inputText value="#{mailAddress.state}" id="state" fs:placeholder="State"/>
				<div class="error-message"><h:message for="state"/></div><br/>
				<!-- Get the zip -->
				<h:inputText value="#{mailAddress.zip}" id="zip" fs:placeholder="Zip" />
				<div class="error-message"><h:message for="zip"/></div><br/>
				
				<h:commandButton value="Save" />
			</h:form>
		</div>
		</ui:define>
	</ui:composition>
</html>

WebContent/BrowseAll.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">

	<ui:composition template="/layouts/CommonLayout.xhtml">
		<ui:define name="title">Browse Products</ui:define>
		<ui:define name="common-content">
			<div align="center">
				<div id="action" class="row">
					<div class="row-title">
						<h:outputText value="Action"/>
					</div>
					<ui:repeat var="movie" value='#{navigationController.movieService.getMoviesByType()}'>
						<div class="single-content">
							<div class="image">
								<h:graphicImage id="#{movie.title}image" url="#{movie.imageURI}" height="333" width="225" /><br/>
							</div>
							<div class="movie-information">
								<h:outputText value="#{movie.title}" /><br/>
								<h:outputText value="Purchase: #{movie.buyPrice}" />
								<h:outputText value="Rent: #{movie.rentPrice}"/><br/>
							</div>
						</div>
					</ui:repeat>
				</div>
			</div>
		</ui:define>
	</ui:composition>
</html>

WebContent/CardInfo.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:fs="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

	<ui:composition template="/layouts/CommonLayout.xhtml">
		<ui:define name="title">Payment Information</ui:define>
		<ui:define name="common-content">
			<div align="center">
			<div align="center">
			<!-- Get the card information -->
			<h:form id="card-info">
				<!-- Get the card number -->
				<h:inputText value="#{card.number}" id="card-number" fs:placeholder="Card Number"/>
				<div class="error-message"><h:message for="card-number"/></div><br/>
				<!-- Name on Card -->
				<h:inputText value="#{card.nameOnCard}" id="card-name" fs:placeholder="Name on Card"/>
				<div class="error-message"><h:message for="card-name"/></div><br/>
				<!-- Expiration date -->
				<h:inputText value="#{card.exDate}" id="card-date" fs:placeholder="Expiration Date"><f:convertDateTime pattern="MM/yy"/></h:inputText>
				<div class="error-message"><h:message for="card-date"/></div><br/>
				<!-- CCV -->
				<h:inputText value="#{card.ccv}" id="card-ccv" fs:placeholder="CCV Code"/>
				<div class="error-message"><h:message for="card-ccv"/></div><br/>
				
					<h:commandButton action="#{userController.SaveCard(card)}" value="Save" rendered="#{card.cardId == -1}"/>
					<h:commandButton action="#{userController.UpdateCard(card)}" value="Update" rendered="#{card.cardId != -1}"/>
				
			</h:form>
		</div>
			<h:form id="address-info">
				<!-- Get the address 1 field -->
				<h:inputText value="#{bill.address1}" id="address1" fs:placeholder="Address 1"/>
				<div class="error-message"><h:message for="address1"/></div><br/>
				<!-- Get the address 2 field -->
				<h:inputText value="#{bill.address2}" id="address2" fs:placeholder="Address 2"/>
				<div class="error-message"><h:message for="address2"/></div><br/>
				<!-- Get the address 3 field -->
				<h:inputText value="#{bill.address3}" id="address3" fs:placeholder="Address 3"/>
				<div class="error-message"><h:message for="address3"/></div><br/>
				<!-- Get the Country field -->
				<h:inputText value="#{bill.country}" id="country" fs:placeholder="Country"/>
				<div class="error-message"><h:message for="country"/></div><br/>
				<!-- Get the city field -->
				<h:inputText value="#{bill.city}" id="city" fs:placeholder="City"/>
				<div class="error-message"><h:message for="city"/></div><br/>
				<!-- Get the state -->
				<h:inputText value="#{bill.state}" id="state" fs:placeholder="State"/>
				<div class="error-message"><h:message for="state"/></div><br/>
				<!-- Get the zip -->
				<h:inputText value="#{bill.zip}" id="zip" fs:placeholder="Zip" />
				<div class="error-message"><h:message for="zip"/></div><br/>
				
				<h:commandButton action="#{userController.SaveBillingAddress(bill)}" value="Save" rendered="#{bill.billingId == -1}"/>
				<h:commandButton action="#{userController.UpdateBillingAddress(bill)}" value="Update" rendered="#{bill.billingId != -1}"/>
			</h:form>
		</div>
		</ui:define>
	</ui:composition>
</html>

WebContent/InputMovie.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:fs="http://xmlns.jcp.org/jsf/passthrough">

<ui:composition template="layouts/CommonLayout.xhtml">
	<ui:define name="title">Registration Menu</ui:define>
	<ui:define name="common-content">
		<div align="center">
			<h:form enctype="multipart/form-data">
				<!-- Get the movie title -->
				<h:inputText value="#{movie.title}" id="title" fs:placeholder="Title" />
				<div class="error-message"><h:message for="title"/></div><br/>
				<!-- Get the purchase price -->
				<h:inputText value="#{movie.buyPrice}" id="purchase-price" fs:placeholder="Purchase Price"/>
				<div class="error-message"><h:message for="purchase-price"/></div><br/>
				<!-- Get the rent price -->
				<h:inputText value="#{movie.rentPrice}" id="rent-price" fs:placeholder="Rent Price"/>
				<div class="error-message"><h:message for="rent-price"/></div><br/>
				<!-- Get the genre -->
				<h:inputText value="#{movie.genre}" id="genre" fs:placeholder="Genre"/>
				<div class="error-message"><h:message for="genre"/></div><br/>
				<!-- Get the movie summary -->
				<h:inputTextarea value="#{movie.summary}" id="summary" fs:placeholder="Summary" rows="5" cols="50"/>
				<div class="error-message"><h:message for="summary"/></div><br/>
				
				 <h:inputFile value="#{movieController.imageFile}"/>
				<!-- TODO find a way to input an image file -->
				
				<h:commandButton action="#{movieController.addMovie(movie)}" value="Add Movie"  />
			</h:form>
		</div>
	</ui:define>
</ui:composition>
</html>

WebContent/Login.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:fs="http://xmlns.jcp.org/jsf/passthrough"> 

<ui:composition template="/layouts/CommonLayout.xhtml">
	<ui:define name="title">Login Menu</ui:define>
	<ui:define name="navigation-bar">
		<h4>Welcome to Movie Madness! Please Sign in to view our products.</h4>
	</ui:define>
	<ui:define name="common-content">
		<div align="center">
				<h:form>
					<h:inputText value="#{user.userName}" id="userName" fs:placeholder="User Name"/>
					<div class="error-message"><h:message for="userName"/></div><br/>
					<h:inputSecret value="#{user.password}" id="password" fs:placeholder="Password"/>
					<div class="error-message"><h:message for="password"/></div><br/>
					<h:commandButton action="#{userController.onLogin(user)}" value="Login" id="login-button" />
					<h:link value="Register" outcome="Register" id="register-button"/> 
				</h:form>
		</div>
	</ui:define>
</ui:composition>
</html>

WebContent/Register.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:fs="http://xmlns.jcp.org/jsf/passthrough"> 

<ui:composition template="layouts/CommonLayout.xhtml">
	<ui:define name="title">Registration Menu</ui:define>
	<ui:define name="navigation-bar">
		<h4>Please make an account here.</h4>
	</ui:define>
	<ui:define name="common-content">
		<div align="center">
			<h:form>
				<h:inputText value="#{user.firstName}" id="firstName" fs:placeholder="First Name"/>
				<div class="error-message"><h:message for="firstName"/></div><br/>
				<h:inputText value="#{user.lastName}" id="lastName" fs:placeholder="Last Name"/>
				<div class="error-message"><h:message for="lastName"/></div><br/>
				<h:inputText value="#{user.userName}" id="userName" fs:placeholder="User Name"/>
				<div class="error-message"><h:message for="userName"/></div><br/>
				<h:inputText value="#{user.email}" id="email" fs:placeholder="Email"/>
				<div class="error-message"><h:message for="email"/></div><br/>
				<h:inputSecret value="#{user.password}" id="password" fs:placeholder="Password"/>
				<div class="error-message"><h:message for="password"/></div><br/>
				<h:link value="Login" outcome="Login" id="login-button"/> 
				<h:commandButton action="#{userController.onRegister(user)}" value="Register" id="register-button" />
			</h:form>
		</div>
	</ui:define>
</ui:composition>
</html>

WebContent/SingleMovie.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:fi="http://xmlns.jcp.org/jsf/html">

	<ui:composition template="/layouts/CommonLayout.xhtml">
		<ui:define name="title"></ui:define>
		<ui:define name="common-content">
		<fi:inputFile></fi:inputFile>
		</ui:define>
	</ui:composition>
</html>

WebContent/UserInfo.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
       xmlns:fs="http://xmlns.jcp.org/jsf/passthrough">

	<ui:composition template="layouts/CommonLayout.xhtml">
	<ui:define name="title">User Info</ui:define>	 	
	<ui:define name="common-content">
		<div align="center">
			<h:form>
				<h:inputText value="#{user.firstName}" id="firstName" fs:placeholder="First Name"/>
				<div class="error-message"><h:message for="firstName"/></div><br/>
				<h:inputText value="#{user.lastName}" id="lastName" fs:placeholder="Last Name"/>
				<div class="error-message"><h:message for="lastName"/></div><br/>
				<h:inputText value="#{user.userName}" id="userName" fs:placeholder="User Name"/>
				<div class="error-message"><h:message for="userName"/></div><br/>
				<h:inputText value="#{user.email}" id="email" fs:placeholder="Email"/>
				<div class="error-message"><h:message for="email"/></div><br/>
				<h:inputSecret value="#{user.password}" id="password" fs:placeholder="Password"/>
				<div class="error-message"><h:message for="password"/></div><br/>
				<h:commandButton action="#{userController.updateUserInfo(user)}" value="Save" />
			</h:form>
		</div>
	</ui:define>
</ui:composition>
</html>